// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoControl.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RazorEnhanced {
  public static partial class ProtoControl
  {
    static readonly string __ServiceName = "protocontrol.ProtoControl";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.RecordRequest> __Marshaller_protocontrol_RecordRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.RecordRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.RecordResponse> __Marshaller_protocontrol_RecordResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.RecordResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.StopRecordRequest> __Marshaller_protocontrol_StopRecordRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.StopRecordRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.StopRecordResponse> __Marshaller_protocontrol_StopRecordResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.StopRecordResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.PlayRequest> __Marshaller_protocontrol_PlayRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.PlayRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.PlayResponse> __Marshaller_protocontrol_PlayResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.PlayResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.StopPlayRequest> __Marshaller_protocontrol_StopPlayRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.StopPlayRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RazorEnhanced.StopPlayResponse> __Marshaller_protocontrol_StopPlayResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RazorEnhanced.StopPlayResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RazorEnhanced.RecordRequest, global::RazorEnhanced.RecordResponse> __Method_Record = new grpc::Method<global::RazorEnhanced.RecordRequest, global::RazorEnhanced.RecordResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Record",
        __Marshaller_protocontrol_RecordRequest,
        __Marshaller_protocontrol_RecordResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RazorEnhanced.StopRecordRequest, global::RazorEnhanced.StopRecordResponse> __Method_StopRecord = new grpc::Method<global::RazorEnhanced.StopRecordRequest, global::RazorEnhanced.StopRecordResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopRecord",
        __Marshaller_protocontrol_StopRecordRequest,
        __Marshaller_protocontrol_StopRecordResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RazorEnhanced.PlayRequest, global::RazorEnhanced.PlayResponse> __Method_Play = new grpc::Method<global::RazorEnhanced.PlayRequest, global::RazorEnhanced.PlayResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Play",
        __Marshaller_protocontrol_PlayRequest,
        __Marshaller_protocontrol_PlayResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RazorEnhanced.StopPlayRequest, global::RazorEnhanced.StopPlayResponse> __Method_StopPlay = new grpc::Method<global::RazorEnhanced.StopPlayRequest, global::RazorEnhanced.StopPlayResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopPlay",
        __Marshaller_protocontrol_StopPlayRequest,
        __Marshaller_protocontrol_StopPlayResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RazorEnhanced.ProtoControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProtoControl</summary>
    [grpc::BindServiceMethod(typeof(ProtoControl), "BindService")]
    public abstract partial class ProtoControlBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Record(global::RazorEnhanced.RecordRequest request, grpc::IServerStreamWriter<global::RazorEnhanced.RecordResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RazorEnhanced.StopRecordResponse> StopRecord(global::RazorEnhanced.StopRecordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Play(global::RazorEnhanced.PlayRequest request, grpc::IServerStreamWriter<global::RazorEnhanced.PlayResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RazorEnhanced.StopPlayResponse> StopPlay(global::RazorEnhanced.StopPlayRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProtoControl</summary>
    public partial class ProtoControlClient : grpc::ClientBase<ProtoControlClient>
    {
      /// <summary>Creates a new client for ProtoControl</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtoControlClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProtoControl that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ProtoControlClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtoControlClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ProtoControlClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RazorEnhanced.RecordResponse> Record(global::RazorEnhanced.RecordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Record(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RazorEnhanced.RecordResponse> Record(global::RazorEnhanced.RecordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Record, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RazorEnhanced.StopRecordResponse StopRecord(global::RazorEnhanced.StopRecordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopRecord(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RazorEnhanced.StopRecordResponse StopRecord(global::RazorEnhanced.StopRecordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopRecord, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RazorEnhanced.StopRecordResponse> StopRecordAsync(global::RazorEnhanced.StopRecordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopRecordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RazorEnhanced.StopRecordResponse> StopRecordAsync(global::RazorEnhanced.StopRecordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopRecord, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RazorEnhanced.PlayResponse> Play(global::RazorEnhanced.PlayRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Play(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::RazorEnhanced.PlayResponse> Play(global::RazorEnhanced.PlayRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Play, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RazorEnhanced.StopPlayResponse StopPlay(global::RazorEnhanced.StopPlayRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopPlay(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RazorEnhanced.StopPlayResponse StopPlay(global::RazorEnhanced.StopPlayRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StopPlay, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RazorEnhanced.StopPlayResponse> StopPlayAsync(global::RazorEnhanced.StopPlayRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StopPlayAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RazorEnhanced.StopPlayResponse> StopPlayAsync(global::RazorEnhanced.StopPlayRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StopPlay, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ProtoControlClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProtoControlClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ProtoControlBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Record, serviceImpl.Record)
          .AddMethod(__Method_StopRecord, serviceImpl.StopRecord)
          .AddMethod(__Method_Play, serviceImpl.Play)
          .AddMethod(__Method_StopPlay, serviceImpl.StopPlay).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProtoControlBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Record, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::RazorEnhanced.RecordRequest, global::RazorEnhanced.RecordResponse>(serviceImpl.Record));
      serviceBinder.AddMethod(__Method_StopRecord, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RazorEnhanced.StopRecordRequest, global::RazorEnhanced.StopRecordResponse>(serviceImpl.StopRecord));
      serviceBinder.AddMethod(__Method_Play, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::RazorEnhanced.PlayRequest, global::RazorEnhanced.PlayResponse>(serviceImpl.Play));
      serviceBinder.AddMethod(__Method_StopPlay, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RazorEnhanced.StopPlayRequest, global::RazorEnhanced.StopPlayResponse>(serviceImpl.StopPlay));
    }

  }
}
#endregion
